general:
    time_frame: 5
    remote_git: 'git@github.com:PedroSena/ConfigHistory.git'
    sections:
      apache2:
        base_directory: '/etc/apache2'
        files_matching: ['.*.conf','magic','sites-enabled/.*']
        ignore_files_matching: 'sites-enabled/teste'