general:
    time_frame: 5
    sections:
      apache2:
        base_directory: '/etc/apache2'
        files_matching: ['.*.conf','magic','sites-enabled/.*']
        ignore_files_matching: 'sites-enabled/teste'